export enum Role {
  FARMER = 'FARMER',
  BUYER = 'BUYER',
  ADMIN = 'ADMIN',
}

export enum VerificationStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum ApprovalStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum CropLotStatus {
  OPEN = 'OPEN',
  BIDDING = 'BIDDING',
  SOLD = 'SOLD',
  CANCELLED = 'CANCELLED',
}

export enum BidStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  WITHDRAWN = 'WITHDRAWN',
}

export enum TransactionStatus {
  INITIATED = 'INITIATED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  INITIATED = 'INITIATED',
  PAID = 'PAID',
  FAILED = 'FAILED',
}

export enum QualityGrade {
  GRADE_A = 'GRADE_A',
  GRADE_B = 'GRADE_B',
  GRADE_C = 'GRADE_C',
}

export enum CropUnit {
  QUINTAL = 'QUINTAL',
  KG = 'KG',
  TONNE = 'TONNE',
}

export enum PriceSource {
  AGMARKNET = 'AGMARKNET',
  MOCK = 'MOCK',
}

export enum AuditAction {
  LOT_CREATED = 'LOT_CREATED',
  BID_PLACED = 'BID_PLACED',
  BID_MODIFIED = 'BID_MODIFIED',
  QUANTITY_MODIFIED = 'QUANTITY_MODIFIED',
  BID_CANCELLED = 'BID_CANCELLED',
  BID_ACCEPTED = 'BID_ACCEPTED',
  BID_REJECTED = 'BID_REJECTED',
  TRANSACTION_COMPLETED = 'TRANSACTION_COMPLETED',
  PAYMENT_PAID = 'PAYMENT_PAID',
  PROFILE_UPDATED = 'PROFILE_UPDATED',
  USER_REGISTERED = 'USER_REGISTERED',
  USER_APPROVED = 'USER_APPROVED',
  USER_REJECTED = 'USER_REJECTED',
}

export enum NotificationType {
  BID_RECEIVED = 'BID_RECEIVED',
  BID_ACCEPTED = 'BID_ACCEPTED',
  BID_REJECTED = 'BID_REJECTED',
  BID_CANCELLED = 'BID_CANCELLED',
  BID_MODIFIED = 'BID_MODIFIED',
  LOT_CREATED = 'LOT_CREATED',
  LOT_SOLD = 'LOT_SOLD',
  PAYMENT_INITIATED = 'PAYMENT_INITIATED',
  PAYMENT_PAID = 'PAYMENT_PAID',
  PROFILE_INCOMPLETE = 'PROFILE_INCOMPLETE',
  SYSTEM = 'SYSTEM',
}
